name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test:cover
      - name: Send coverage to Codacy
        run: |
          if [ $CODACY_PROJECT_TOKEN ]; then
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
              --coverage-reports ./coverage/salary-stats/lcov.info \
              --language TypeScript \
              --project-token $CODACY_PROJECT_TOKEN
          fi
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/salary-stats/lcov.info'
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - run: npm run build:docker
      - run: npm run e2e
  deploy:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Get full tag
        id: full_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Get major and minor versions
        id: versions
        run: |
          echo "MAJOR=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "MINOR=$(echo $VERSION | cut -d. -f2)" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ steps.full_tag.outputs.VERSION }}
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: ./bin/prepare-deploy.sh
        env:
          TAG: ${{ steps.full_tag.outputs.VERSION }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          build-args: |
            ALPINE_RELEASE=3.17
            NODE_RELEASE=${{ steps.nvmrc.outputs.NODE_VERSION }}
          push: true
          tags: |
            textbook/salary-stats
            textbook/salary-stats:${{ steps.full_tag.outputs.VERSION }}
            textbook/salary-stats:${{ steps.versions.outputs.MAJOR }}
            textbook/salary-stats:${{ steps.versions.outputs.MAJOR }}.${{ steps.versions.outputs.MINOR }}
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: textbook/salary-stats
      - run: |
          gh release create \
            '${{ steps.full_tag.outputs.VERSION }}' \
            --title '${{ steps.full_tag.outputs.VERSION }}' \
            'dist-${{ steps.full_tag.outputs.VERSION }}.tar.gz'
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist-ghp
